title: My Portfolio
description: >- # this means to ignore newlines until "baseurl:"
  My Portfolio
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: "https://sunny-smiles.github.io" # the base hostname & protocol for your site
theme: minima # specify the Jekyll theme here
