title: Fikri Majid's Portfolio
description: A simple portfolio site
baseurl: "/portfolio" # adjust if your site is under a subpath
url: "https://sunny-smiles.github.io" # replace with your GitHub Pages URL
theme: minima
